### ISSUE TITLE
Request, not issue

### ISSUE THREAD

**Issue by Zazarothh** [mastertea/RandomPlus#2]
Howdy, sorry for posting this here. Couldn't really find a way to request this. But was wondering if there was an option to edit the roll limit. I've modified the RandomSettings.cs to 500, 1000, 10000, and 100000. but doesn't change the value in game. What am i doing wrong?

**Comment by mastertea** [comment]
You need to compile the code.

**Comment by Zazarothh** [comment]
Never done it before but have to learn. Thank you

**Comment by Zazarothh** [comment]
Loaded the correct Solution, made the edit I would like. Tried to build and get 200+ errors. Am I not linking something?

**Comment by mastertea** [comment]
My guess is that you haven't yet added a reference to rimworlds game libraries. Find the location of where rimworld is installed in your system and include these as references in you project.

"Rimworld install location"\RimWorldWin64_Data\Managed\UnityEngine.dll
"Rimworld install location"\RimWorldWin64_Data\Managed\Assembly-CSharp.dll

You may have to google how to include references in your particular IDE.

**Comment by Zazarothh** [comment]
That was it. Thank you so much for your time. Learned something today :)
